baseurl = "/"
languageCode = "en-us"
title = "timelson.com"
theme = "xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
enableEmoji = true
pygmentsUseClasses = false
pygmentsStyle = "friendly"
pygmentsCodefences = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
    description = "Blog using Hugo."
    footer = "&copy; [timelson.com](http://timelson.com) 2017 -- 2018 | [Github](https://github.com/eL0ck)"

